export const queryKeys = {
  authUser: ["authUser"],
  user: (id: string) => ["user", id],
  friends: (id: string, page: number) => ["friends", page, id],
  allFriends: (id: string) => ["allFriends", id],
  friendship: (id: string) => ["friendship", id],
  friendReqest: (id: string) => ["friendRequests", id],
  friendRequestCount: ["friendRequestCount"],
  latestParties: ["latestParties"],
  partyId: (id: string) => ["partyId", id],
  postsByUser: (id: string, page: number) => ["postByUser", page, id],
  postsByPartyId: (id: string) => ["postById", id],
  post: (id: string) => ["post", id],
  partyAttendanceMe: (id: string) => ["partyAttendanceMe", id],
  partyPosts: (id: string) => ["partyPosts", id],
  partyAttendance: (id: string) => ["partyAttendance", id],
  partyHistory: (id: string) => ["partyHistory", id],
  comments: (postId: string, page: number) => ["comments", postId, page],
  commentsInf: (postId: string) => ["comments", postId],
} as const;
